[versions]
lwjava = "0.3.1"
lwkotlin = "0.3.3"
kotestVersion= "1.3.3"
kotlin = "2.1.21"
dokka = "1.9.20"
jvm = "11"
antlr = "4.13.1"
gson = "2.10.1"
kotlinCsv = "1.9.2"
kotlinXmlBuilder = "1.7.3"
clikt = "3.5.0"
specsVersion = "0.1.6-SNAPSHOT"

[plugins]
buildConfig = { id = "com.github.gmazzo.buildconfig", version = "5.3.5" }
superPublish = { id = "com.vanniktech.maven.publish", version = "0.22.0" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version = "11.5.1" }

[libraries]
lionwebjava = { group = "io.lionweb.lionweb-java", name = "lionweb-java-2024.1-core", version.ref = "lwjava" }
lionwebjavaemf = { group = "io.lionweb.lionweb-java", name = "lionweb-java-2024.1-emf", version.ref = "lwjava" }
lionwebkotlinrepoclient = { group = "io.lionweb.lionweb-kotlin", name = "lionweb-kotlin-2024.1-repo-client", version.ref = "lwkotlin" }
lionwebkotlinrepoclienttesting = { group = "io.lionweb.lionweb-kotlin", name = "lionweb-kotlin-2024.1-repo-client-testing", version.ref = "lwkotlin" }
lionwebkotlincore = { group = "io.lionweb.lionweb-kotlin", name = "lionweb-kotlin-2024.1-core", version.ref = "lwkotlin" }
kotesttestcontainers = { module = "io.kotest.extensions:kotest-extensions-testcontainers", version.ref = "kotestVersion" }
antlr = { module = "org.antlr:antlr4", version.ref = "antlr" }
antlrRuntime = { module = "org.antlr:antlr4-runtime", version.ref = "antlr" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
kotlinCsv = { module = "com.github.doyaaaaaken:kotlin-csv-jvm", version.ref = "kotlinCsv" }
kotlinXmlBuilder = { module = "org.redundent:kotlin-xml-builder", version.ref = "kotlinXmlBuilder" }
clikt = { module = "com.github.ajalt.clikt:clikt", version.ref = "clikt" }
starlasu-specs = { module="com.strumenta.starlasu.specs:starlasuspecs-jvm", version.ref="specsVersion" }
