[versions]
lwjava = "0.4.4"
lwkotlin = "0.4.1"
kotestVersion= "1.3.3"
specsVersion = "0.2.0-SNAPSHOT"
gson = "2.13.0"

[plugins]
buildConfig = { id = "com.github.gmazzo.buildconfig", version = "5.4.0" }
# More recent versions og this plugin to do not work with JVM 8
# We should configure JVM 11 for the build and JVM 8 only as a target
superPublish = { id = "com.vanniktech.maven.publish", version = "0.22.0" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version = "11.5.1" }

[libraries]
lionwebjava = { group = "io.lionweb.lionweb-java", name = "lionweb-java-2024.1-core", version.ref = "lwjava" }
lionwebjavaemf = { group = "io.lionweb.lionweb-java", name = "lionweb-java-2024.1-emf", version.ref = "lwjava" }
lionwebjavarepoclienttesting = { group = "io.lionweb.lionweb-java", name = "lionweb-java-2024.1-repo-client-testing", version.ref = "lwjava" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
lionwebkotlinrepoclient = { group = "io.lionweb.lionweb-kotlin", name = "lionweb-kotlin-2024.1-repo-client", version.ref = "lwkotlin" }
lionwebkotlincore = { group = "io.lionweb.lionweb-kotlin", name = "lionweb-kotlin-2024.1-core", version.ref = "lwkotlin" }
kotesttestcontainers = { module = "io.kotest.extensions:kotest-extensions-testcontainers", version.ref = "kotestVersion" }
starlasu-specs = { module="com.strumenta.starlasu.specs:starlasuspecs-jvm", version.ref="specsVersion" }
