[versions]
antlr4 = "4.9.3"

[libraries]
gson = { module = "com.google.code.gson:gson", version = "2.10.1" }
antlr4Tool = { module = "org.antlr:antlr4", version.ref = "antlr4" }
antlr4jRuntime = { module = "org.antlr:antlr4-runtime", version.ref= "antlr4" }
clikt = { module = "com.github.ajalt.clikt:clikt", version="3.5.2"}

[plugins]
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version = "12.1.1" }
buildconfig = { id = "com.github.gmazzo.buildconfig", version = "3.1.0" }
gradlepublish = { id = "com.gradle.plugin-publish", version = "1.2.1" }
