[plugins]
buildConfig = { id = "com.github.gmazzo.buildconfig", version = "5.3.5" }
superPublish = { id = "com.vanniktech.maven.publish", version = "0.22.0" }

[versions]
lwjava = "0.2.18"
lwkotlin = "0.2.4"

[libraries]
lionwebjava = { group = "io.lionweb.lionweb-java", name = "lionweb-java-2023.1-core", version.ref = "lwjava" }
lionwebjavaemf = { group = "io.lionweb.lionweb-java", name = "lionweb-java-2023.1-emf", version.ref = "lwjava" }
lionwebkotlinrepoclient = { group = "io.lionweb.lionweb-kotlin", name = "lionweb-kotlin-2024.1-repo-client", version.ref = "lwkotlin" }
lionwebkotlinrepoclienttesting = { group = "io.lionweb.lionweb-kotlin", name = "lionweb-kotlin-2024.1-repo-client-testing", version.ref = "lwkotlin" }
lionwebkotlincore = { group = "io.lionweb.lionweb-kotlin", name = "lionweb-kotlin-2024.1-core", version.ref = "lwkotlin" }
