[plugins]
buildConfig = { id = "com.github.gmazzo.buildconfig", version = "5.3.5" }
superPublish = { id = "com.vanniktech.maven.publish", version = "0.27.0" }

[versions]
lwkotlin = "0.2.2-SNAPSHOT"

[libraries]
lionwebjava = { group = "io.lionweb.lionweb-java", name = "lionweb-java-2023.1-core", version = "0.2.17" }
lionwebkotlinrepoclient = { group = "io.lionweb.lionweb-kotlin", name = "lionweb-kotlin-2024.1-repo-client", version.ref = "lwkotlin" }
lionwebkotlinrepoclienttesting = { group = "io.lionweb.lionweb-kotlin", name = "lionweb-kotlin-2024.1-repo-client-testing", version.ref = "lwkotlin" }
lionwebkotlincore = { group = "io.lionweb.lionweb-kotlin", name = "lionweb-kotlin-2024.1-core", version.ref = "lwkotlin" }
