[versions]
antlr4 = "4.9.3"
lwjava = "0.4.4"
lwkotlin = "0.4.1"
kotestVersion= "2.0.2"
specsVersion = "0.1.8"

[plugins]
buildConfig = { id = "com.github.gmazzo.buildconfig", version = "5.4.0" }
# More recent versions og this plugin to do not work with JVM 8
# We should configure JVM 11 for the build and JVM 8 only as a target
superPublish = { id = "com.vanniktech.maven.publish", version = "0.22.0" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version = "11.5.1" }
gradlePublish = { id = "com.gradle.plugin-publish", version = "1.2.1" }
kover = { id = "org.jetbrains.kotlinx.kover", version = "0.8.3" }

[libraries]
lionwebjava = { group = "io.lionweb.lionweb-java", name = "lionweb-java-2024.1-core", version.ref = "lwjava" }
lionwebjavaemf = { group = "io.lionweb.lionweb-java", name = "lionweb-java-2024.1-emf", version.ref = "lwjava" }
gson = { module = "com.google.code.gson:gson", version = "2.11.0" }
antlr4Tool = { module = "org.antlr:antlr4", version.ref = "antlr4" }
antlr4jRuntime = { module = "org.antlr:antlr4-runtime", version.ref= "antlr4" }
clikt = { module = "com.github.ajalt.clikt:clikt", version="4.4.0"}
lionwebkotlinrepoclient = { group = "io.lionweb.lionweb-kotlin", name = "lionweb-kotlin-2024.1-repo-client", version.ref = "lwkotlin" }
lionwebkotlinrepoclienttesting = { group = "io.lionweb.lionweb-kotlin", name = "lionweb-kotlin-2024.1-repo-client-testing", version.ref = "lwkotlin" }
lionwebkotlincore = { group = "io.lionweb.lionweb-kotlin", name = "lionweb-kotlin-2024.1-core", version.ref = "lwkotlin" }
kotesttestcontainers = { module = "io.kotest.extensions:kotest-extensions-testcontainers", version.ref = "kotestVersion" }
starlasu-specs = { module="com.strumenta.starlasu.specs:starlasuspecs-jvm", version.ref="specsVersion" }
