<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="RpgAst" nsURI="https://strumenta.com/rpgast" nsPrefix="rpgast">
  <eClassifiers xsi:type="ecore:EClass" name="CompileTimeArray" eSuperTypes="https://strumenta.com/kolasu/v1#//Named https://strumenta.com/kolasu/v1#//ASTNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lines" upperBound="-1"
        eType="ecore:EDataType https://strumenta.com/kolasu/v1#//string"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" lowerBound="1" eType="ecore:EDataType https://strumenta.com/kolasu/v1#//int"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArrayType" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ascend" eType="ecore:EDataType https://strumenta.com/kolasu/v1#//boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="compileTimeRecordsPerLine"
        eType="ecore:EDataType https://strumenta.com/kolasu/v1#//int"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="element" eType="#//Type"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nElements" lowerBound="1"
        eType="ecore:EDataType https://strumenta.com/kolasu/v1#//int"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NumberType" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="decimal" lowerBound="1"
        eType="ecore:EDataType https://strumenta.com/kolasu/v1#//boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="decimalDigits" lowerBound="1"
        eType="ecore:EDataType https://strumenta.com/kolasu/v1#//int"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="entireDigits" lowerBound="1"
        eType="ecore:EDataType https://strumenta.com/kolasu/v1#//int"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="integer" lowerBound="1"
        eType="ecore:EDataType https://strumenta.com/kolasu/v1#//boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfDigits" lowerBound="1"
        eType="ecore:EDataType https://strumenta.com/kolasu/v1#//int"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rpgType" eType="ecore:EDataType https://strumenta.com/kolasu/v1#//string"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CharacterType" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nChars" lowerBound="1"
        eType="ecore:EDataType https://strumenta.com/kolasu/v1#//int"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TimeStampType" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="LowValType" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="HiValType" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanType" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="StringType" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="length" lowerBound="1"
        eType="ecore:EDataType https://strumenta.com/kolasu/v1#//int"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="varying" lowerBound="1"
        eType="ecore:EDataType https://strumenta.com/kolasu/v1#//boolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FieldType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType https://strumenta.com/kolasu/v1#//string"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Type" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataStructureType" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elementSize" lowerBound="1"
        eType="ecore:EDataType https://strumenta.com/kolasu/v1#//int"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fields" upperBound="-1"
        eType="#//FieldType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="KListType" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="FigurativeType" eSuperTypes="#//Type"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractDataDefinition" abstract="true"
      eSuperTypes="https://strumenta.com/kolasu/v1#//ASTNode https://strumenta.com/kolasu/v1#//Named">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Type" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true" eSuperTypes="https://strumenta.com/kolasu/v1#//ASTNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="FieldDefinition" eSuperTypes="#//AbstractDataDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="calculatedEndOffset" eType="ecore:EDataType https://strumenta.com/kolasu/v1#//int"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="calculatedStartOffset"
        eType="ecore:EDataType https://strumenta.com/kolasu/v1#//int"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="declaredArrayInLine" eType="ecore:EDataType https://strumenta.com/kolasu/v1#//int"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="declaredArrayInLineOnThisField"
        eType="ecore:EDataType https://strumenta.com/kolasu/v1#//int"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="descend" lowerBound="1"
        eType="ecore:EDataType https://strumenta.com/kolasu/v1#//boolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endOffset" lowerBound="1"
        eType="ecore:EDataType https://strumenta.com/kolasu/v1#//int"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="explicitEndOffset" eType="ecore:EDataType https://strumenta.com/kolasu/v1#//int"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="explicitStartOffset" eType="ecore:EDataType https://strumenta.com/kolasu/v1#//int"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initializationValue" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" lowerBound="1" eType="ecore:EDataType https://strumenta.com/kolasu/v1#//int"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startOffset" lowerBound="1"
        eType="ecore:EDataType https://strumenta.com/kolasu/v1#//int"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stepSize" lowerBound="1"
        eType="ecore:EDataType https://strumenta.com/kolasu/v1#//int"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataDefinition" eSuperTypes="#//AbstractDataDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fields" upperBound="-1"
        eType="#//FieldDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initializationValue" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inz" lowerBound="1" eType="ecore:EDataType https://strumenta.com/kolasu/v1#//boolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Directive" abstract="true" eSuperTypes="https://strumenta.com/kolasu/v1#//ASTNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="Statement" abstract="true" eSuperTypes="https://strumenta.com/kolasu/v1#//ASTNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="StatementThatCanDefineData" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="InStatementDataDefinition" eSuperTypes="#//AbstractDataDefinition">
    <eStructuralFeatures xsi:type="ecore:EReference" name="initializationValue" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PlistParam" eSuperTypes="https://strumenta.com/kolasu/v1#//ASTNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataDefinition" eType="#//InStatementDataDefinition"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="param" eType="ecore:EClass https://strumenta.com/kolasu/v1#//ReferenceByName"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PlistStmt" eSuperTypes="#//Statement #//StatementThatCanDefineData">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isEntry" lowerBound="1"
        eType="ecore:EDataType https://strumenta.com/kolasu/v1#//boolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="params" upperBound="-1"
        eType="#//PlistParam" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FileDefinition" eSuperTypes="https://strumenta.com/kolasu/v1#//ASTNode https://strumenta.com/kolasu/v1#//Named">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="internalFormatName" eType="ecore:EDataType https://strumenta.com/kolasu/v1#//string"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MainBody" eSuperTypes="https://strumenta.com/kolasu/v1#//ASTNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="stmts" upperBound="-1"
        eType="#//Statement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Subroutine" eSuperTypes="https://strumenta.com/kolasu/v1#//Named https://strumenta.com/kolasu/v1#//ASTNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="stmts" upperBound="-1"
        eType="#//Statement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tag" eType="ecore:EDataType https://strumenta.com/kolasu/v1#//string"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompilationUnit" eSuperTypes="https://strumenta.com/kolasu/v1#//ASTNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="compileTimeArrays" upperBound="-1"
        eType="#//CompileTimeArray" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataDefinitions" upperBound="-1"
        eType="#//DataDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="directives" upperBound="-1"
        eType="#//Directive" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entryPlist" eType="#//PlistStmt"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fileDefinitions" upperBound="-1"
        eType="#//FileDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="main" eType="#//MainBody"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subroutines" upperBound="-1"
        eType="#//Subroutine" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
