<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="SimpleMM" nsURI="https://strumenta.com/simplemm" nsPrefix="simplemm">
  <eClassifiers xsi:type="ecore:EClass" name="Statement" abstract="true" eSuperTypes="https://strumenta.com/kolasu/v1#//ASTNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true" eSuperTypes="https://strumenta.com/kolasu/v1#//ASTNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="StringLiteral" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType https://strumenta.com/kolasu/v1#//string"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Visibility">
    <eLiterals name="PUBLIC"/>
    <eLiterals name="PRIVATE" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VarDeclaration" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="initialValue" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType https://strumenta.com/kolasu/v1#//string"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" lowerBound="1"
        eType="#//Visibility"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompilationUnit" eSuperTypes="https://strumenta.com/kolasu/v1#//ASTNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1"
        eType="#//Statement" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
