name: Build and Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        # For building we need JDK 11
        java: [ '11', '17', '21' ]
    name: Java ${{ matrix.Java }} BuildAndTest

    steps:
    - uses: actions/checkout@v1
    - name: Setup java
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: ${{ matrix.java }}
    - name: Check Java version
      run: java -version
    - name: Test
      run: ./gradlew check
