name: PublishLocally

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8', '11', '13', '15', '16' ]
    name: Java ${{ matrix.Java }} Publish

    steps:
    - uses: actions/checkout@v1
    - name: Setup java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: ${{ matrix.java }}
    - name: Publish to local
      run: ./gradlew publishToMavenLocal